
version: "1.0"
stages:
  - "clone"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "https://github.com/amit-kashyap-wawa/testcontainer"
    revision: "master"
    stage: "clone"

